language: python
python:
- '3.6'
install: pip install -r requirements.txt
script: make publish
cache: pip
before_deploy:
- openssl aes-256-cbc -K $encrypted_2c65ff4ef9b8_key -iv $encrypted_2c65ff4ef9b8_iv
  -in travis_rsa.enc -out /tmp/travis_rsa -d
- chmod 400 /tmp/travis_rsa
- eval "$(ssh-agent -s)"
- ssh-add /tmp/travis_rsa
addons:
  ssh_known_hosts: fsantiago.info
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-before --quiet $TRAVIS_BUILD_DIR/output/* fsantiago@fsantiago.info:/home/fsantiago/fsantiago.info/content
  on:
    branch: master
